# .github/workflows/upload-build-to-release.yml
# This workflow executes tests.
# It is used as a validation mechanism for PRs.
name: Run tests
permissions: read-all
on:
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.7.0

      - name: Run tests
        run: devbox run test
