# .github/workflows/run-tests.yml
# This workflow executes tests.
# It is used as a validation mechanism for PRs.
name: Run tests
permissions: read-all
on:
  pull_request:
    branches:
      - "**"
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install devbox environment
        uses: jetpack-io/devbox-install-action@v0.8.0
      - name: Run tests
        run: devbox run test
