# .github/workflows/upload-build-to-release.yml
# This workflow generates monorepo builds.
# Then, it uploads them to the latest release.
name: Upload build to latest release
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_run_id: ${{ steps.build_upload.outputs.run_id }}
    steps:
      - name: Checkout to latest release tag
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}
      - name: Build monorepo and upload artifacts
        id: build_upload
        uses: ./github/workflows/build-monorepo.yml
        with:
          build_tag: ${{ github.ref }}
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download bombastic build artifact
        run: gh run download ${{ needs.build.outputs.artifact_run_id }}
      - name: Upload artifacts to release
        run: |
          gh release upload ${{ github.ref }} \
            bombastic-${{ github.ref }}.zip \
            bombastic-cli${{ github.ref }}-x86_64
