# .github/workflows/upload-build-to-release.yml
# This workflow generates monorepo builds.
# Then, it uploads them to the latest release.
name: Upload build to latest release
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build_release_assets:
    uses: ./.github/workflows/build-monorepo.yml
    with:
      build_tag: ${{ github.ref }}
  upload_release_assets:
    runs-on: ubuntu-latest
    needs: build_release_assets
    steps:
      - name: Download bombastic build artifact
        run: gh run download ${{ needs.build_release_assets.outputs.run_id }}
      - name: Upload artifacts to release
        run: |
          gh release upload ${{ github.ref }} \
            bombastic-${{ github.ref }}.zip \
            bombastic-cli${{ github.ref }}-x86_64
